---
- name: Configure ospf with Jinja
  hosts: routers
  gather_facts: no
  tasks:
    - name: Configure loopbacks
      ios_config:
        src: loopbacks.j2

    - name: Upload ospf cfg file
      ios_config:
        src: ospf.j2

#testing templates
    - name: ospf template
      template:
        src: ospf.j2
        dest: test-ospf.txt

    - name: ospf template
      template:
        src: loopbacks.j2
        dest: test-lo.txt

    