---
- name: Configure ospf with Jinja
  hosts: routers
  gather_facts: no
  tasks:
    - name: Configure loopbacks
      ios_config:
        src: loopbacks.j2

    - name: Upload ospf cfg file
      ios_config:
        src: ospf.j2

#testing templates
#    - name: ospf template
#      template:
#        src: ospf.j2
#        dest: test-ospf.txt
#
#    - name: ospf template
#      template:
#        src: loopbacks.j2
#        dest: test-lo.txt
#    - name: ospf template
#      template:
#        src: ospf_auth.j2
#        dest: test-auth.txt

### check: show ip ospf interface Gi0

    - name: Add authentication to OSPF mgmt int
      ios_config:
        src: ospf_auth.j2

###
    - name: Collect ospf neighbor outputs
      ios_command:
        commands:
          - show ip ospf neighbor
      register: ospf_neighbors

    - name: Collect ospf route outputs
      ios_command:
        commands:
          - show ip route ospf
      register: ospf_routes

    - debug:
        msg: 
          - "{{ inventory_hostname }} OSPF Neighbors:"
          - "{{ ospf_neighbors.stdout[0] | regex_findall('(?:[0-9]{1}\\.){3}[0-9]{1}') }}"

    - debug:
        msg: 
          - "Number of OSPF learned routes: {{ ospf_routes.stdout[0] | regex_findall('O\\D{8}\\d{1}') | count }}"

    - name: save running to startup when modified
      ios_config:
        save_when: always

    