inventory_hostname: R1
inventory_ip: 192.168.56.103

#lab4
rid: 1.1.1.1

loopbacks:
  - name: lo0
    ip: 10.1.0.1 #/26
    ip_net: 10.1.0.0
    ip_netmask: 255.255.255.192
    ip_wild: 0.0.0.63
    description: Office area
    ospf_area: 1
  - name: lo1
    ip: 10.3.0.1 #/25
    ip_net: 10.3.0.0
    ip_netmask: 255.255.255.128
    ip_wild: 0.0.0.127
    description: Conference area
    ospf_area: 2
